[build]
  command = """
    corepack enable &&
    corepack prepare pnpm@10.26.0 --activate &&
    cd /opt/build/repo &&
    pnpm install --frozen-lockfile &&
    pnpm turbo build --filter=api...[origin/main]
  """
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[functions]
  included_files = ["src/docs/swagger.yaml"]
